### ISSUE TITLE
Renewing SSL certicates

### ISSUE THREAD

**Issue by moisesrodriguez** [suchorski/keycloak-docker-compose#4] opened 2024-11-04 22:05 UTC
@suchorski my SSL certificates were not renewing with `up certbot`:

```
docker compose -f /path/to/docker-compose.yml up certbot && docker compose -f /path/to/docker-compose.yml exec nginx nginx -s reload
```

I changed it to `run certbot renew --webroot -w /var/www/certbot`:

```
docker compose -f /path/to/docker-compose.yml run certbot renew --webroot -w /var/www/certbot && docker compose -f /path/to/docker-compose.yml exec nginx nginx -s reload
```

And now they are renewing

**Comment by suchorski** [comment] 2024-11-04 23:43
Mine is working with my command... checked now and renewed 13 days ago

**Comment by suchorski** [comment] 2024-11-04 23:44
Duplicate of #3

**Closed as completed** 2024-11-05 00:46 UTC
Labels: duplicate
